// Writes the no-op OpenGL ES 3.0 the shim hands Flycast when the module has no canvas (Node:
// bench.mjs, check.mjs), from Khronos' gl3.h. Flycast reaches every GL function through
// libretro's get_proc_address (glsm/glsym), so the shim answers with these instead of
// Emscripten's WebGL ones and the renderer sets itself up, walks the PowerVR scene each frame and
// draws nothing. The machine (SH4, PowerVR registers and VRAM, AICA, GD-ROM) runs exactly as in
// the page: Flycast never reads the picture back into the machine (no render-to-VRAM, no
// framebuffer emulation; see shim/vab_flycast.cpp), so states and RAM match the browser's.
//   node gl_null.mjs <path to GLES3/gl3.h> > gl_null.c
import { readFileSync } from "node:fs";

const header = readFileSync(process.argv[2], "utf8");
const prototypes = /^GL_APICALL\s+(.+?)\s*GL_APIENTRY\s+(gl\w+)\s*\((.*)\);/gm;

let out = `// Generated by flycast/shim/gl_null.mjs from Khronos' GLES3/gl3.h: do not edit.
#include <GLES3/gl3.h>
#include <stdlib.h>
#include <string.h>

static GLuint next_id = 1;
static void *mapped;

`;
const names = [];
for (const [, type, name, params] of header.matchAll(prototypes)) {
  const args = params === "void" ? [] : params.split(",").map((p) => p.trim().split(/[\s*]+/).pop());
  let body;
  if (name === "glCreateShader" || name === "glCreateProgram") body = "return next_id++;";
  else if (/^glGen[A-Z]/.test(name)) body = `for (GLsizei i = 0; i < ${args[0]}; i++) ${args[1]}[i] = next_id++;`;
  else if (name === "glGetShaderiv" || name === "glGetProgramiv")
    body = "*params = (pname == GL_COMPILE_STATUS || pname == GL_LINK_STATUS || pname == GL_VALIDATE_STATUS) ? GL_TRUE : 0;";
  else if (name === "glGetShaderInfoLog" || name === "glGetProgramInfoLog")
    body = "if (length) *length = 0; if (bufSize > 0) infoLog[0] = 0;";
  else if (name === "glGetShaderPrecisionFormat") body = "range[0] = 127; range[1] = 127; *precision = 23;";
  else if (name === "glCheckFramebufferStatus") body = "return GL_FRAMEBUFFER_COMPLETE;";
  else if (name === "glGetString")
    body = `switch (name) {
    case GL_VERSION: return (const GLubyte *)"OpenGL ES 3.0 (no-op GL)";
    case GL_SHADING_LANGUAGE_VERSION: return (const GLubyte *)"OpenGL ES GLSL ES 3.00";
    case GL_VENDOR: return (const GLubyte *)"vab";
    case GL_RENDERER: return (const GLubyte *)"no-op GL";
    default: return (const GLubyte *)"";
  }`;
  else if (name === "glGetStringi") body = 'return (const GLubyte *)"";';
  else if (name === "glGetIntegerv")
    body = `switch (pname) {
    case GL_MAJOR_VERSION: *data = 3; break;
    case GL_MAX_TEXTURE_SIZE: case GL_MAX_RENDERBUFFER_SIZE: *data = 8192; break;
    case GL_MAX_VIEWPORT_DIMS: data[0] = data[1] = 8192; break;
    case GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: *data = 32; break;
    case GL_MAX_TEXTURE_IMAGE_UNITS: case GL_MAX_VERTEX_ATTRIBS: *data = 16; break;
    case GL_MAX_SAMPLES: case GL_MAX_DRAW_BUFFERS: case GL_MAX_COLOR_ATTACHMENTS: *data = 4; break;
    case GL_IMPLEMENTATION_COLOR_READ_FORMAT: *data = GL_RGBA; break;
    case GL_IMPLEMENTATION_COLOR_READ_TYPE: *data = GL_UNSIGNED_BYTE; break;
    default: *data = 0; break;
  }`;
  else if (/^glGet(Float|Boolean|Integer64)v$/.test(name)) body = "*data = 0;";
  else if (name === "glGetUniformLocation") body = "return (GLint)next_id++;";
  else if (name === "glMapBufferRange") body = "free(mapped); mapped = calloc(1, length ? length : 1); return mapped;";
  else if (name === "glUnmapBuffer") body = "free(mapped); mapped = NULL; return GL_TRUE;";
  else if (name === "glFenceSync") body = "return (GLsync)(size_t)next_id++;";
  else if (name === "glClientWaitSync") body = "return GL_ALREADY_SIGNALED;";
  else if (type === "void") body = "";
  else body = "return 0;";
  out += `static ${type} null_${name}(${params})\n{\n  ${args.map((n) => `(void)${n};`).join(" ")}\n  ${body}\n}\n\n`;
  names.push(name);
}
// WebGL2's, not in gl3.h (Flycast's glsym asks for it).
out += "static void null_glGetBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, void *data)\n{\n  (void)target; (void)offset; (void)size; (void)data;\n}\n\n";
names.push("glGetBufferSubData");
out += `typedef struct { const char *name; void (*fn)(void); } NullGLEntry;
static const NullGLEntry entries[] = {
${names.map((n) => `  { "${n}", (void (*)(void))null_${n} },`).join("\n")}
};

// The no-op function called \`name\`, or NULL for one OpenGL ES 3.0 doesn't have (as WebGL2 would).
void (*vab_null_gl_proc(const char *name))(void)
{
  for (size_t i = 0; i < sizeof(entries) / sizeof(entries[0]); i++)
    if (!strcmp(entries[i].name, name)) return entries[i].fn;
  return NULL;
}
`;
process.stdout.write(out);
